# yaml-language-server: $schema=https://raw.githubusercontent.com/cncf/landscape2/refs/heads/main/docs/config/schema/settings.schema.json

# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: Bundesverband Green Software

url: http://127.0.0.1:8000 # TODO

colors:
  color1: "rgba(37, 58, 1, 1)" # Buttons, groups, links
  color2: "rgba(176, 201, 94, 1)" # Some highlighted items like filters button, search icon
  color3: "rgba(176, 201, 94, 1)" # Participation stats bars, spinners, modal titles
  color4: "rgba(37, 58, 1, 1)" # Categories titles in filters, fieldset in filters modal
  color5: "rgba(26, 108, 104, 1)" # Categories and subcategories frames (odd)
  color6: "rgba(26, 108, 104, 1)" # Categories and subcategories frames (even)
  color7: "rgba(26, 108, 104, 1)" # Borders, shadows and options boxes in games

featured_items: # TODO
  - field: maturity
    options:
      - value: proved+tested
        order: 1
        label: BVGS Proved & Tested
  - field: subcategory
    options:
      - value: <VALUE 1>
      - value: <VALUE 2>

footer:
  links:
    homepage: https://www.bundesverband-green-software.de
    linkedin: https://www.linkedin.com/company/bundesverband-green-software/
    # github: <GITHUB_URL>
  logo: https://www.bundesverband-green-software.de/images/BVGS_Logo.webp
  text: |
    Copyright Â© 2025 Bundesverband Green Software

grid_items_size: large

groups:
  - name: Measurement
    categories:
      - Cloud Application Measurement
      - AI Model Measurement
      - Desktop Application Measurement
      - Mobile App Measurement
      - CI Pipeline Measurement
      - Component Measurement (Test Environment)
      - Arbitrary Software Measurement
      - Unix System Measurement
      - Website Measurement
      - Code Measurement (Development Environment)
      - Static Code Analysis
  - name: Optimization
    categories:
      - Cloud Optimization (GreenOps)
      - Kubernetes Optimization
      - Carbon Aware Applications
  - name: Data Management
    categories:
      - IT Inventory
      - Usage Data

# Specify order, if relevant
# categories:
#   - name: Cloud Application Measurement
#     subcategories:
#       - Manual Data Input
#       - Automated Usage Data Retrieval
#       - Continuous Data Recording

header:
  # links:
  #   github: <GITHUB_URL>
  logo: https://www.bundesverband-green-software.de/images/BVGS_Logo.webp

images:
  favicon: https://www.bundesverband-green-software.de/images/BVGS_Icon_32x32.ico

screenshot_width: 1500
